products/urls.py
from django.urls import path
from . import views


app_name = 'products'


urlpatterns = [

    path('',views.index, name = 'home'),
    path('new',views.new)

]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 
urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls'))
]

products/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField()
    stock = models.IntegerField()
    Image_url = models.CharField(max_length=2086)
    

class offer(models.Model):
    code = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    discount = models.FloatField()

products/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product
# Create your views here.

def index (request):
    products = Product.objects.all()
    return render(request,'index.html',{'products':products})


def new (request):
    return HttpResponse('New')

shop/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

products/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Shop</title>
  </head>
  <body>
     {% block content %}
     {% endblock %}             }

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

products/templates/index.html
{% extends 'base.html'%}

{% block content %}


<h1>Products</h1>
<div class = "row">
            {%  for Product in products  %} 
    
    <div class = "col">
        
        <div class="card" style="width: 18rem;">
            <img src="{{ Product.Image_url }}" class="card-img-top" alt=" ">
            <div class="card-body">
              <h5 class="card-title">{{ Product.name }}</h5>
              <p class="card-text">{{ Product.price }}</p>
              <a href="#" class="btn btn-primary">Add to Cart</a>
            </div>
          </div>
    
    
    
    

        </div>
            {% endfor %}
</div> 



    
    {% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css"
    href="{% static 'css/style.css' %}">

    <title>Shop</title>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Shop</a>
      </nav>
    </div>
    <div class="container">

      {% block content %}
     {% endblock %} 

    </div>
                 }

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html'%}
{% load static %}



<!DOCTYPE html>
<html>
  
<head>
<title>HTML Tutorial</title>
<link rel="stylesheet" type="text/css"
      href="{% static 'css/style.css' %}">


</head>
<body>
  {% block content %}
        <nav id = "navbar">
          <div class = "container">
            <ul>
          <li><a>Home</a></li>
          <li><a href="{% url 'products:home' %}">products</a></li>
          <li><a>About</a></li>
          <li><a>Contacts</a></li>
          
            </ul>
        </div>
      </nav>
    
      <section id = "view">
      <div class = "container">
        <h1>This is Our Online website.We welcome you for happy shopping.have a nice day

        </h1>


      </div>



      </section>
      <footer id = "main-footer">
        <p>Copyright &copy; 2020 My Website</p>

      </footer>
      {% endblock %}
</body>

</html>